name: Release

on:
  push:
    # run only against tags
    tags:
      - "v*.*.*"

env:
  GO_VERSION: 1.25
  GO_RELEASER_VERSION: v2.4.7
  
permissions: {}

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write

      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: false
    - name: Set up cross-compilers
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: ${{ env.GO_RELEASER_VERSION }}
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
