# This workflow is managed by gh actions-lock.

name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0

    - name: Set up Go
      uses: actions/setup-go@v4.3.0
      with:
        go-version: '1.25'

    - name: Test
      run: go test -v ./...
